### PR TITLE
Adding request timeout option

### PR DESCRIPTION
**Pull request by rfink**
Addresses #17

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@rfink great work, but need to fix the unit test. 500 is too much. Test sing 1 or 2 only.
After unit test are fixed I can merge and release.

**Comment by rfink** [comment]
Thanks!  1 or 2, as in 100 or 200 milliseconds?

**Comment by rfink** [comment]
I went ahead and set it to 1 millisecond and 2 milliseconds, respectively.  I hope clock drift doesn't play with the tests too much.

**Comment by claudiosmweb** [comment]
@rfink no worry. But I think I'll remove this test... since it is making travis crazy and we don't need test timeout, since it's from the `request` module and not our function.
Thanks man :)

**Comment by rfink** [comment]
Thanks again!

**Pull request merged**
